In [2]:
import tensorflow as tf
#tf.constant(value)=>返回常量tensor
hello_constant = tf.constant('Hello World')
#tf.Session() 创建session环境来运行 tensor求值
with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output)

b'Hello World'


In [4]:
#tf.placeholder(valueType) =>返回可变的tensor
x= tf.placeholder(tf.string)

with tf.Session() as sess:
    #feed_dict在sess.run()中表示设置站位tensor。
    output = sess.run(x,feed_dict={x:'Hellow World'})
    print(output)

Hellow World


In [12]:
#注意，这个东西可以设置很多歌站位tensor
y=tf.placeholder(tf.int32)
z=tf.placeholder(tf.float32)

with tf.Session() as sess:
    #feed_dict相当于是对 某个声明的placeholder赋值，但是还是没搞明白赋值多个值有什么意思
    output = sess.run(z,feed_dict={y:1234,z:34.3})
    print(output)

34.3


In [22]:
a = tf.constant(12)
b = tf.constant(13.0)

#类型转换
a = tf.cast(a,tf.float32)
#加法
c =tf.add(a,b)
#减法
d = tf.subtract(a,b)
#乘法
e = tf.multiply(a,b)
#除法
f= tf.divide(a,b)
with tf.Session() as se:
    print(se.run(f))
    print(type(c))


0.9230769
<class 'tensorflow.python.framework.ops.Tensor'>


In [29]:
#可以改变的tensor
x = tf.Variable(5)
with tf.Session() as se:
    se.run(x.initializer)
    print(se.run(x))

5


In [32]:
n_features=12
n_labels=5
#返回一个 tensor，它的随机值取自一个正态分布，并且它们的取值会在这个正态分布平均值的两个标准差之内
weights =tf.Variable(tf.truncated_normal((n_features,n_labels)))

with tf.Session() as se:
    se.run(weights.initializer)
    print(se.run(weights))

[[ 0.80020833  1.0476861  -1.6716974   1.9024004   0.68187433]
 [ 0.818476    0.77752465 -1.3180068  -0.616964   -0.71439725]
 [-0.4636816  -0.31636056  0.5836321   1.2463789  -0.5435934 ]
 [-0.99956924  0.8085113   0.7159128   0.42563555  0.04177723]
 [ 1.1234915   0.4923074  -0.41198066 -0.1070033   0.7845778 ]
 [-1.283885    0.24439937  0.19811116  0.31681356  0.18062514]
 [ 1.7092242  -0.4290254  -1.9820449  -0.490221    0.96343607]
 [-0.8648838   1.0050249  -0.58878547  0.08637504 -0.5159742 ]
 [-0.4325987  -0.5995777  -0.6444781  -0.73774695 -0.913574  ]
 [ 0.5124484   0.12590504  0.20967291 -0.2894685  -1.0461934 ]
 [ 1.7206411  -0.03080015  0.17789046 -1.5323759  -0.8534149 ]
 [ 0.39032784 -0.31696212 -1.5443692  -0.19574638 -0.18145324]]


In [ ]:
#返回都是0的tensor
tf.zeros()